# Site settings
title: Larry Blog
SEOTitle: Larry的博客 | Larry Blog
header-img: img/home-bg.jpg
email: func_dev@126.com
description: "这里是 @Larry 的个人博客"
keyword: "刘晓东，Larry，个人博客，iOS，Flutter，OC/Swift/Dart，移动互联网开发，大前端开发"
url: "https://wuxuange.com" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: Larry
zhihu_username: Larry
github_username: Larry
twitter_username: Larry
#facebook_username:  Larry
#linkedin_username:  Larry

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: Larry

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics (https://tongji.baidu.com/main/setting/10000573707/home/site/index)
ba_track_id: 7dc016ed3ed3019aa6f4ed3f8b088e04

# Google Analytics (https://analytics.google.com/analytics/web/#/p403176009/reports/reportinghub)
ga_track_id: "G-KPS91REP8N" # Format: UA-xxxxxx-xx
ga_domain: wuxaunge.com

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "程序从0和1开始"
sidebar-avatar: https://github.com/LarryLib.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "0", href: "http://wuxuange.com/" },
    { title: "1", href: "https://wuxuange.com/" },
  ]
