language: ruby
cache: bundler
rvm:
  - &latest_ruby 2.7
  - 2.5

env:
  - JEKYLL_VERSION="~> 3.8"

matrix:
  include:
    - # GitHub Pages
      rvm: 2.5.3
      env: GH_PAGES=true
    - rvm: *latest_ruby
      env: JEKYLL_VERSION=">= 4.0.0"

before_install:
  - gem update --system
  - bundle update
script : script/cibuild
